name: publish
on:
  push:
    branches: [main]
    paths-ignore:
      - "README.md"
      - "LICENCE"
      - "config.example.toml"
      - ".gitignore"
  pull_request:
    branches: [main]
    paths-ignore:
      - "README.md"
      - "LICENCE"
      - "config.example.toml"
      - ".gitignore"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login with Github Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Publish to Github Container registry
        run: |
          docker build . --tag ghcr.io/mhthies/ews-caldav-sync:latest
          docker push ghcr.io/mhthies/ews-caldav-sync:latest
